// <auto-generated />
using System;
using KanGainNET.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KanGainNET.Migrations
{
    [DbContext(typeof(SilowniaContext))]
    [Migration("20260527134233_PolaczeniePlanyZCwiczeniami")]
    partial class PolaczeniePlanyZCwiczeniami
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CwiczeniePlanTreningowy", b =>
                {
                    b.Property<int>("CwiczeniaId")
                        .HasColumnType("int");

                    b.Property<int>("PlanyTreningoweId")
                        .HasColumnType("int");

                    b.HasKey("CwiczeniaId", "PlanyTreningoweId");

                    b.HasIndex("PlanyTreningoweId");

                    b.ToTable("CwiczeniePlanTreningowy");
                });

            modelBuilder.Entity("KanGainNET.Models.Cwiczenie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cwiczenia");
                });

            modelBuilder.Entity("KanGainNET.Models.Grafik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataKoniec")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataStart")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PracownikId")
                        .HasColumnType("int");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.Property<int?>("ZajeciaGrupoweId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PracownikId");

                    b.HasIndex("SalaId");

                    b.HasIndex("ZajeciaGrupoweId");

                    b.ToTable("Grafiki");
                });

            modelBuilder.Entity("KanGainNET.Models.KartaRFID", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktywna")
                        .HasColumnType("bit");

                    b.Property<string>("UID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("KartyRFID");
                });

            modelBuilder.Entity("KanGainNET.Models.Lokalizacja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Dlugosc")
                        .HasPrecision(12, 8)
                        .HasColumnType("decimal(12,8)");

                    b.Property<string>("Miasto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Szerokosc")
                        .HasPrecision(12, 8)
                        .HasColumnType("decimal(12,8)");

                    b.HasKey("Id");

                    b.ToTable("Lokalizacje");
                });

            modelBuilder.Entity("KanGainNET.Models.Obecnosc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("KartaRFIDId")
                        .HasColumnType("int");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UzytkownikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KartaRFIDId");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("Obecnosci");
                });

            modelBuilder.Entity("KanGainNET.Models.PlanTreningowy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataStworzenia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PracownikId")
                        .HasColumnType("int");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PracownikId");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("PlanyTreningowe");
                });

            modelBuilder.Entity("KanGainNET.Models.Platnosc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPlatnosci")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Kwota")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Metoda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubskrypcjaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubskrypcjaId");

                    b.ToTable("Platnosci");
                });

            modelBuilder.Entity("KanGainNET.Models.PomiarCiala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPomiaru")
                        .HasColumnType("datetime2");

                    b.Property<double>("TkankaTluszczowa")
                        .HasColumnType("float");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.Property<double>("Waga")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("PomiaryCiala");
                });

            modelBuilder.Entity("KanGainNET.Models.Pracownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataZatrudnienia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Specjalizacja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UzytkownikId")
                        .IsUnique();

                    b.ToTable("Pracownicy");
                });

            modelBuilder.Entity("KanGainNET.Models.ProfilUzytkownika", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UzytkownikId")
                        .IsUnique();

                    b.ToTable("ProfileUzytkownikow");
                });

            modelBuilder.Entity("KanGainNET.Models.Rabat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcentZnizki")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rabaty");
                });

            modelBuilder.Entity("KanGainNET.Models.Rezerwacja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GrafikId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrafikId");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("Rezerwacje");
                });

            modelBuilder.Entity("KanGainNET.Models.Rola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("KanGainNET.Models.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LokalizacjaId")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pojemnosc")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LokalizacjaId");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("KanGainNET.Models.Sprzet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LokalizacjaId")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StanTechniczny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LokalizacjaId");

                    b.ToTable("Sprzet");
                });

            modelBuilder.Entity("KanGainNET.Models.Subskrypcja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataKonca")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataStartu")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypKarnetuId")
                        .HasColumnType("int");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypKarnetuId");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("Subskrypcje");
                });

            modelBuilder.Entity("KanGainNET.Models.TypKarnetu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cena")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CzasTrwaniaDni")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypyKarnetow");
                });

            modelBuilder.Entity("KanGainNET.Models.Uzytkownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRejestracji")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolaId");

                    b.ToTable("Uzytkownicy");
                });

            modelBuilder.Entity("KanGainNET.Models.ZajeciaGrupowe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ZajeciaGrupowe");
                });

            modelBuilder.Entity("CwiczeniePlanTreningowy", b =>
                {
                    b.HasOne("KanGainNET.Models.Cwiczenie", null)
                        .WithMany()
                        .HasForeignKey("CwiczeniaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KanGainNET.Models.PlanTreningowy", null)
                        .WithMany()
                        .HasForeignKey("PlanyTreningoweId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KanGainNET.Models.Grafik", b =>
                {
                    b.HasOne("KanGainNET.Models.Pracownik", "Pracownik")
                        .WithMany("Grafiki")
                        .HasForeignKey("PracownikId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KanGainNET.Models.Sala", "Sala")
                        .WithMany("Grafiki")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KanGainNET.Models.ZajeciaGrupowe", "ZajeciaGrupowe")
                        .WithMany("Grafiki")
                        .HasForeignKey("ZajeciaGrupoweId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pracownik");

                    b.Navigation("Sala");

                    b.Navigation("ZajeciaGrupowe");
                });

            modelBuilder.Entity("KanGainNET.Models.KartaRFID", b =>
                {
                    b.HasOne("KanGainNET.Models.Uzytkownik", "Uzytkownik")
                        .WithMany()
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("KanGainNET.Models.Obecnosc", b =>
                {
                    b.HasOne("KanGainNET.Models.KartaRFID", "KartaRFID")
                        .WithMany()
                        .HasForeignKey("KartaRFIDId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KanGainNET.Models.Uzytkownik", null)
                        .WithMany("Obecnosci")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KartaRFID");
                });

            modelBuilder.Entity("KanGainNET.Models.PlanTreningowy", b =>
                {
                    b.HasOne("KanGainNET.Models.Pracownik", "Trener")
                        .WithMany("PlanyTreningowe")
                        .HasForeignKey("PracownikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KanGainNET.Models.Uzytkownik", "Uzytkownik")
                        .WithMany()
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trener");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("KanGainNET.Models.Platnosc", b =>
                {
                    b.HasOne("KanGainNET.Models.Subskrypcja", "Subskrypcja")
                        .WithMany("Platnosci")
                        .HasForeignKey("SubskrypcjaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subskrypcja");
                });

            modelBuilder.Entity("KanGainNET.Models.PomiarCiala", b =>
                {
                    b.HasOne("KanGainNET.Models.Uzytkownik", "Uzytkownik")
                        .WithMany()
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("KanGainNET.Models.Pracownik", b =>
                {
                    b.HasOne("KanGainNET.Models.Uzytkownik", "Uzytkownik")
                        .WithOne("Pracownik")
                        .HasForeignKey("KanGainNET.Models.Pracownik", "UzytkownikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("KanGainNET.Models.ProfilUzytkownika", b =>
                {
                    b.HasOne("KanGainNET.Models.Uzytkownik", "Uzytkownik")
                        .WithOne("Profil")
                        .HasForeignKey("KanGainNET.Models.ProfilUzytkownika", "UzytkownikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("KanGainNET.Models.Rezerwacja", b =>
                {
                    b.HasOne("KanGainNET.Models.Grafik", "Grafik")
                        .WithMany("Rezerwacje")
                        .HasForeignKey("GrafikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KanGainNET.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("Rezerwacje")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grafik");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("KanGainNET.Models.Sala", b =>
                {
                    b.HasOne("KanGainNET.Models.Lokalizacja", "Lokalizacja")
                        .WithMany("Sale")
                        .HasForeignKey("LokalizacjaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lokalizacja");
                });

            modelBuilder.Entity("KanGainNET.Models.Sprzet", b =>
                {
                    b.HasOne("KanGainNET.Models.Lokalizacja", "Lokalizacja")
                        .WithMany("Sprzety")
                        .HasForeignKey("LokalizacjaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lokalizacja");
                });

            modelBuilder.Entity("KanGainNET.Models.Subskrypcja", b =>
                {
                    b.HasOne("KanGainNET.Models.TypKarnetu", "TypKarnetu")
                        .WithMany("Subskrypcje")
                        .HasForeignKey("TypKarnetuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KanGainNET.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("Subskrypcje")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TypKarnetu");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("KanGainNET.Models.Uzytkownik", b =>
                {
                    b.HasOne("KanGainNET.Models.Rola", "Rola")
                        .WithMany("Uzytkownicy")
                        .HasForeignKey("RolaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rola");
                });

            modelBuilder.Entity("KanGainNET.Models.Grafik", b =>
                {
                    b.Navigation("Rezerwacje");
                });

            modelBuilder.Entity("KanGainNET.Models.Lokalizacja", b =>
                {
                    b.Navigation("Sale");

                    b.Navigation("Sprzety");
                });

            modelBuilder.Entity("KanGainNET.Models.Pracownik", b =>
                {
                    b.Navigation("Grafiki");

                    b.Navigation("PlanyTreningowe");
                });

            modelBuilder.Entity("KanGainNET.Models.Rola", b =>
                {
                    b.Navigation("Uzytkownicy");
                });

            modelBuilder.Entity("KanGainNET.Models.Sala", b =>
                {
                    b.Navigation("Grafiki");
                });

            modelBuilder.Entity("KanGainNET.Models.Subskrypcja", b =>
                {
                    b.Navigation("Platnosci");
                });

            modelBuilder.Entity("KanGainNET.Models.TypKarnetu", b =>
                {
                    b.Navigation("Subskrypcje");
                });

            modelBuilder.Entity("KanGainNET.Models.Uzytkownik", b =>
                {
                    b.Navigation("Obecnosci");

                    b.Navigation("Pracownik")
                        .IsRequired();

                    b.Navigation("Profil")
                        .IsRequired();

                    b.Navigation("Rezerwacje");

                    b.Navigation("Subskrypcje");
                });

            modelBuilder.Entity("KanGainNET.Models.ZajeciaGrupowe", b =>
                {
                    b.Navigation("Grafiki");
                });
#pragma warning restore 612, 618
        }
    }
}
